packages:
  - .
  - example/*

ignoredBuiltDependencies:
  - better-sqlite3

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sqlite3

scripts:
  approval:
    esbuild: true
    sqlite3: true
