/* Parse the JSON intermediate representation generated by planner-agents to proper Agentlang workflows */

import { isString } from '../util.js';

export function workflowFromJson(json: string): string {
  const obj = JSON.parse(json);
  const wf: any | undefined = obj.workflow;
  if (wf && !wf.event) {
    throw new Error('workflow name not specified in generated JSON');
  }
  const pObjs: any[] | undefined = wf?.patterns || obj.patterns;
  if (pObjs === undefined) {
    throw new Error('No patterns found in generater JSON');
  }
  const pats = pObjs
    .map((patObj: any) => {
      return asPattern(patObj);
    })
    .join(';\n');

  if (wf === undefined) {
    return `[${pats}]`;
  } else {
    return `workflow ${wf.event} {
        ${pats}
     }`;
  }
}

function asPattern(pObj: any): string {
  if (pObj.create) {
    return asCreate(pObj);
  } else if (pObj.query) {
    return asQuery(pObj);
  } else if (pObj.update) {
    return asUpdate(pObj);
  } else if (pObj.delete) {
    return asDelete(pObj);
  } else if (pObj.if) {
    return asIf(pObj);
  } else if (pObj.for) {
    return asFor(pObj);
  } else {
    throw new Error(`Invalid pattern object: ${pObj}`);
  }
}

function asCreate(pObj: any): string {
  const n: string | undefined = pObj.create;
  if (n === undefined) {
    throw new Error(`Entity, event or record name missing in ${pObj}`);
  }
  const ss = asAttributes(pObj.with);
  const result = `{${n} {
    ${ss.join(',\n')}
    }}`;
  const alias: string | undefined = pObj.as;
  if (alias === undefined) return result;
  else return `${result} @as ${alias}`;
}

function asUpdate(pObj: any): string {}

function asDelete(pObj: any): string {}

function asQuery(pObj: any): string {}

function asIf(pObj: any): string {}

function asFor(pObj: any): string {}

function asAttributes(attrsObj: any): string[] {
  if (attrsObj === undefined) {
    attrsObj = {};
  }
  return Object.keys(attrsObj).map((k: string) => {
    const spec: any = attrsObj[k];
    let v: any = spec.ref || spec.expr;
    if (v === undefined) {
      v = spec.val;
      if (isString(v)) {
        v = `"${v}"`;
      }
    }
    return `${k} ${v}`;
  });
}

function asQueryAttributes(whereObj: any): string[] {
    return Object.keys(whereObj)
}
