name: AppCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  test_library_app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installing fractl-io dependancies
        run: |
          git clone https://${{ secrets.REPO_READ_WRITE_TOKEN }}@github.com/fractl-io/fractl-config-secrets-reader
          cd fractl-config-secrets-reader
          lein install
      - name: Install dependencies
        run: lein deps
      - name: Install Node JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Newman cli install
        run: npm install -g newman
      - name: Run lein library app & Newman API test
        run: |
          lein run sample/library/model.fractl &
          sleep 180
          newman run sample/library/library-ci.postman_collection.json
          kill -9 `lsof -i:8000 -t`
        env:
          API_HOST: 127.0.0.1:8000
          CI: true
