name: ClojureScriptCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  test_cljs:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout & Setup
      uses: actions/checkout@v2
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.0
      with:
        cli: '1.10.1.469'
        lein: 2.9.4
        boot: latest
    - name: Install maven dependency
      run: mvn install:install-file -Dfile=lib/alasql-0.6.5-0.jar -DgroupId=cljsjs -DartifactId=alasql -Dversion=0.6.5-0 -Dpackaging=jar
    - name: Install dependencies
      run: lein deps
    # - name: Run cljs test
    #   run: clojure -m figwheel.main -fwo '{:open-url "http://[[server-hostname]]:[[server-port]]" :watch-dirs ["src" "test"] :log-syntax-error-style :concise :launch-js ["/opt/google/chrome/chrome" "--headless" "--disable-gpu" "--repl" "--disable-dev-shm" :open-url]' -m fractl.test-runner
    - name: Run cljs test
      run: lein fig:ci
    - name: Slack Notification
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
        SLACK_CHANNEL: ci
        SLACK_FOOTER: Cookie! Om nom nom nom
        SLACK_TITLE: 'All cool. More COOKIES! :cookie: :cookie:'
        SLACK_MESSAGE: 'Om Nom Nom :cookie:'
        SLACK_ICON: https://avatars3.githubusercontent.com/u/10654370?size=48
        SLACK_USERNAME: Cookie Monster
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Slack Notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
        SLACK_CHANNEL: ci
        SLACK_FOOTER: Cookie! Om nom nom nom
        SLACK_TITLE: 'It Failed! No cookies.'
        SLACK_MESSAGE: 'No cookie? :cry:'
        SLACK_COLOR: '#ff1100'
        SLACK_ICON_EMOJI: ':scream:'
        SLACK_USERNAME: Cookie Monster
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

