name: FractlCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install maven dependency
      run: mvn install:install-file -Dfile=lib/alasql-0.6.5-0.jar -DgroupId=cljsjs -DartifactId=alasql -Dversion=0.6.5-0 -Dpackaging=jar
    - name: Install dependencies
      run: lein deps
    # TODO: Update main test to check whether Fractl works for a simple app
