name: "Publish new release"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    name: Publish new release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # only merged pull requests must trigger this job
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: lein deps
      - name: Generate pom.xml needed for mvn deploy
        run: lein pom

      - name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

#      This feature is removed for now, as we do not depend upon Github Package Registry for jar files.
#      Additionally, it causes some issue during mvn packaging.
#      - name: Deploy to Github Package Registry
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          mkdir -p ~/.m2
#          echo "<settings><servers><server><id>github</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
#          mvn deploy

      - name: Generate jar, uberjar and copy them to lib.
        run: |
          lein jar
          lein uberjar
          cp -r target/fractl-${{env.RELEASE_VERSION}}.jar lib/
          cp -r target/fractl-${{env.RELEASE_VERSION}}-standalone.jar lib/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.event.pull_request.merge_commit_sha }}
          tag: ${{ env.RELEASE_VERSION }}
          artifacts: "lib/fractl-${{env.RELEASE_VERSION}}.jar,lib/fractl-${{env.RELEASE_VERSION}}-standalone.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

      - name: Cleanup jar
        run |
          rm -r lib/fractl-${{env.RELEASE_VERSION}}.jar
          rm -r lib/fractl-${{env.RELEASE_VERSION}}-standalone.jar
          lein clean

      - name: Slack Notification
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_CHANNEL: releases
          SLACK_FOOTER: Fractl Release Notification
          SLACK_TITLE: 'Release packaging successful'
          SLACK_MESSAGE: ${{ github.event.release.tag_name }}
          SLACK_USERNAME: Release Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_CHANNEL: releases
          SLACK_FOOTER: Fractl Release Notification
          SLACK_TITLE: 'Release packaging failed'
          SLACK_MESSAGE: ${{ github.event.release.tag_name }}
          SLACK_COLOR: '#ff1100'
          SLACK_USERNAME: Release Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
